blogist/blog/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', landing, name='landing'),
    path('home/', index, name='home'),
    path('api/category/create/', category_create, name='cat_create'),
    path('api/tag/create/', tag_create, name='tag_create'),
    path('api/image/upload/', image_upload, name='image_create'),
    path('article/new/', article_create, name='create'),
    path('article/<int:id>/view/', article_view, name='view'),
    path('article/search/', search_article, name='search'),
]

blogist/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('account/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogist/blog/models.py
from django.db import models
from django.conf import settings
# pip install `django-tinymce` for the import below
from tinymce.models import HTMLField

class Category(models.Model):
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Image(models.Model):
    image = models.ImageField(upload_to='articles/images/')
    caption = models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)    

    def __str__(self):
        return self.image.url

class Article(models.Model):

    class StatusChoice(models.IntegerChoices):
        DRAFT = 0, 'Draft'
        PUBLISHED = 1, 'Published'
    
    title = models.CharField(max_length=100, unique=True)
    publish_date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    status = models.IntegerField(choices=StatusChoice.choices, default=StatusChoice.DRAFT)
    tags = models.ManyToManyField(Tag)
    duration = models.DurationField()
    content = HTMLField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.title} by {self.author}'

blogist/blog/forms.py
from django import forms
from .models import Category, Tag, Image, Article
from tinymce.widgets import TinyMCE

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name',)

class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ('name',)

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('image','caption')

class ArticleForm(forms.ModelForm):
    content = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 20},))
    status  = forms.ChoiceField(choices=Article.StatusChoice.choices, widget=forms.RadioSelect)
    category = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label='Select Category')
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.CheckboxSelectMultiple)
    duration = forms.DurationField(widget=forms.TimeInput(attrs={'type': 'time'}))
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'}))

    class Meta:
        model = Article
        fields = ('title','content','category','tags','status','duration')
        

blogist/blog/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import *
from django.contrib import messages
from django.conf import settings

def index(request):
    ctx = {}
    articles = Article.objects.filter(status=1)
    ctx['title'] = 'Home'
    ctx['articles'] = articles
    return render(request, 'blog/index.html', ctx)

def landing(request):
    ctx = {}
    ctx['title'] = 'Welcome to Blogist'
    return render(request, 'blog/landing.html', ctx)

def article_create(request):
    ctx = {'title': 'Create Article | Blogist'}
    article_form = ArticleForm(request.POST or None)
    category_form = CategoryForm()
    tag_form = TagForm()
    image_form = ImageForm()
    if article_form.is_valid():
        # print("Form data")
        # print(article_form.cleaned_data)
        article = article_form.save(commit=False) # save the form partially
        article.author = request.user 
        article.save()
        messages.success(request, 'Article created successfully')  

    ctx['article_form'] = article_form
    ctx['category_form'] = category_form
    ctx['tag_form'] = tag_form
    ctx['image_form'] = image_form
    return render(request, 'blog/create.html', ctx)

# ajax base views
def category_create(request):
    if request.method == 'POST':
        category_form = CategoryForm(request.POST)
        if category_form.is_valid():
            cat = category_form.save(commit=False)
            cat.save()
            return JsonResponse({'status': 'success', 'name': cat.name, 'id': cat.id})
        else:
            return JsonResponse({'status': 'invalid data'})
    else:
        return JsonResponse({'status': 'error'})

def tag_create(request):
    if request.method == 'POST':
        tag_form = TagForm(request.POST)
        if tag_form.is_valid():
            tag = tag_form.save(commit=False)
            tag.save()
            return JsonResponse({'status': 'success', 'name': tag.name, 'id': tag.id})
        else:
            return JsonResponse({'status': 'invalid data'})
    else:
        return JsonResponse({'status': 'error'})

def image_upload(request):
    if request.method == 'POST':
        image_form = ImageForm(request.POST, request.FILES)
        print(image_form)
        if image_form.is_valid():
            image = image_form.save(commit=False)
            image.save()
            return JsonResponse({'status': 'success', 'name': image.image.name, 'id': image.id})
        else:
            return JsonResponse({'status': 'invalid data'})
    else:
        return JsonResponse({'status': 'error'})

def article_view(request, id):
    ctx = {}
    article = get_object_or_404(Article, id=id)
    ctx['title'] = article.title
    ctx['article'] = article
    return render(request, 'blog/detail.html', ctx)

def search_article(request):
    ctx = {}
    query = request.GET.get('q')
    # print(query)
    ctx['articles'] = Article.objects.filter(content__icontains=query).filter(status=1)
    ctx['q'] = query
    return render(request, 'blog/search.html',ctx)

blogist/templates/blog/create.html
{% extends 'layout/base.html' %}
{% load static %}
{% load django_bootstrap5 %}


{% block content %}
<div class="container-fluid p-3 mx-auto">
    <div class="row">
        <div class="col-md-9 p-5 border-end mt-5">
            <h1 class="display1">Write your Article ✒️</h1>
            <form method="post">
                {% csrf_token %}
                {% bootstrap_form article_form %}
                <!-- this line is important -->
                {{ article_form.media }}
                {% bootstrap_button "Save" type="submit" %}
            </form>
        </div>
        <div class="col-md-3 px-5 mt-5 border-end">
            <div class="card mb-3 border-0">
                <div class="card-header bg-transparent border-0">
                    <h3 class="card-title">Add Media</h3>
                </div>
                <form action="" method="post" class="card-body" id="media-form" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% csrf_token %}
                    {% bootstrap_form image_form %}
                    {% bootstrap_button "Add Media" type="submit" %}
                </form>
            </div>

            <div class="card mb-3 border-0">
                <div class="card-header bg-transparent border-0">
                    <h3>Add New Category</h3>
                </div>
                <form method="post" class="card-body" id="catform">
                    {% csrf_token %}
                    {% bootstrap_form category_form %}
                    {% bootstrap_button "Add Category" type="submit" %}
                </form>
            </div>
            <div class="card border-0">
                <div class="card-header bg-transparent border-0">
                    <h3 class="card-title">Add Tags</h3>
                </div>
                <form action="" method="post" class="card-body" id="tagform">
                    {% csrf_token %}
                    {% bootstrap_form tag_form %}
                    {% bootstrap_button "Add Tags" type="submit" %}
                </form>

            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block css %}
<style>
    #id_tags,
    #id_status {
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        align-content: center;
        justify-content: flex-start;
        align-items: flex-end;
    }

    #id_tags>.form-check,
    #id_status>.form-check {
        margin: 0 2rem 1rem 0;
    }
</style>
{% endblock %}


{% block js %}
<script src="https://code.jquery.com/jquery-3.6.1.min.js"
    integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
<script src="{% static 'js/create.js' %}"></script>



{% endblock %}

blogist/templates/blog/detail.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <h1 class="display-1">{{article.title}}</h1>
            <p class="lead">{{article.content|safe}}</p>
        </div>
    </div>
</div>
{% endblock %}

blogist/templates/blog/index.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}

<div class="p-5 mb-4 bg-light shadow-sm   hero">
    <div class="container py-5">
        <h1 class="fw-bold display-1">
            Blog<span class="text-success">ist</span>
        </h1>
        <p class="col-md-8 fs-4">
            Welcome to Blogist, a awesome blog app for training purposes of students of Digipodium.
            Built with 💗 using Django, Sqlite and Bootstrap 5.
        </p>
        <div class="search-wrapper">
            <div class="container search-btn">
                <button class="btn btn-outline-dark btn-lg" type="button">
                    <i class="bi bi-search"></i> Search
                </button>
            </div>
            <div class="container d-none" id="search-box">
                <form class="d-flex" action="{% url 'search' %}">
                    <input class="form-control form-control-lg me-2 px-5 py-1" type="search" placeholder="Search"
                        aria-label="Search" name="q">
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="bi bi-search h4"></i>
                        </button>
                        <button class="btn btn-dark" type="button" id="close-search">
                            <i class="bi bi-x"></i>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">

        {% for item in articles %}
        <div class="col-md-5">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        <a href="{% url 'view' item.id %}" class="nav-link">
                            {{item.title}}
                        </a>
                    </h3>
                </div>
                <div class="card-body">
                    <p>{{item.content|safe|truncatechars:250 }}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <p>no articles published</p>
        {% endfor %}

    </div>
</div>
{% endblock %}
{% block css %}
<style>
    .hero {
        background-image: url('{% static "images/hero-01.png" %}');
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
    }
</style>
{% endblock %}
{% block js %}
<script>
    let searchBtn = document.querySelector('.search-btn');
    let searchBox = document.querySelector('#search-box');
    let closeSearch = document.querySelector('#close-search');

    searchBtn.addEventListener('click', () => {
        searchBox.classList.toggle('d-none');
        searchBtn.classList.toggle('d-none');
    });
    closeSearch.addEventListener('click', () => {
        searchBox.classList.toggle('d-none');
        searchBtn.classList.toggle('d-none');
    });
</script>
{% endblock %}

blogist/templates/blog/landing.html
{% load static %}


{% block css %}
<style>
    body {
        background-color: rgb(20, 20, 20);
        margin: 0px;
    }

    #menu {
        height: 100vh;
        width: 100vw;
        display: flex;
        align-items: center;
    }

    .menu-item {
        color: white;
        font-size: clamp(3rem, 8vw, 8rem);
        font-family: Arial, Helvetica, sans-serif;
        text-decoration: none;
        display: block;
        padding: clamp(.25rem, .5vw, 1rem) 0rem;
        transition: all 400ms;

    }

    #menu-items {
        margin-left: clamp(4rem, 20vw, 48rem);
        position: relative;
        z-index: 2;
    }

    #menu-items:hover>.menu-item {
        opacity: .1;
    }

    #menu-items:hover>.menu-item:hover {
        opacity: 1;
        font-size: clamp(3rem, 12vw, 12rem);
        color: chocolate;
    }

    #menu-background-pattern {
        height: 100vh;
        width: 100vw;
        background-image: radial-gradient(rgba(255, 255, 255, 0.1) 9%, transparent 9%);
        background-position: 0% 0%;
        background-size: 12vmin 12vmin;
        position: absolute;
        left: 0;
        top: 0;
        z-index: 1;
        transition: all 800ms ease;
    }

    #menu-background-image {
        height: 100%;
        width: 100%;
        background-image: url('https://images.unsplash.com/photo-1614094082869-cd4e4b2905c7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80');
        position: absolute;
        left: 0;
        top: 0;
        z-index: 0;
        background-position: top 40%;
        background-size: 110vmax;
        opacity: .15;
        transition: all 800ms ease;
    }

    #menu-items:hover>#menu-background-pattern {
        background-size: 100vmax;
        orphans: .1;
    }

    #menu-items:hover~#menu-background-pattern {
        background-size: 11vmin 11vmin;
        opacity: .5;
    }

    /* move background pattern */
    #menu[data-active-index="0"]>#menu-background-pattern {
        background-position: 0% -25%;
    }

    #menu[data-active-index="1"]>#menu-background-pattern {
        background-position: 0% -50%;
    }

    #menu[data-active-index="2"]>#menu-background-pattern {
        background-position: 0% -75%;
    }

    #menu[data-active-index="3"]>#menu-background-pattern {
        background-position: 0% -100%;
    }

    #menu[data-active-index="4"]>#menu-background-pattern {
        background-position: 0% -125%;
    }

    /* move background image */
    #menu[data-active-index="0"]>#menu-background-image {
        background-position: center 20%;
    }

    #menu[data-active-index="1"]>#menu-background-image {
        background-position: center 35%;
    }

    #menu[data-active-index="2"]>#menu-background-image {
        background-position: center 50%;
    }

    #menu[data-active-index="3"]>#menu-background-image {
        background-position: center 75%;
    }

    #menu[data-active-index="4"]>#menu-background-image {
        background-position: center 100%;
    }

    #logo {
        position: absolute;
        top: -50px;
        right: 0;
    }
</style>
{% endblock %}

{% block content %}
<div id="menu">
    <div id="menu-items">
        <a href="{% url 'home' %}" class="menu-item">Articles</a>
        <a href="{% url 'create' %}" class="menu-item">Create</a>
        <a href="#" class="menu-item">Categories</a>
        <a href="#" class="menu-item">About</a>
        <a href="#" class="menu-item">Search</a>
    </div>
    <div id="menu-background-pattern"></div>
    <div id="menu-background-image"></div>
    <img id="logo" src="{% static 'images/logo.png' %}" alt="logo">
</div>
{% endblock %}


{% block js %}
<script>
    let menu = document.querySelector("#menu");
    Array.from(document.querySelectorAll('.menu-item'))
        .forEach((item, index) => {
            item.onmouseover = () => {
                menu.dataset.activeIndex = index;
            }
        });
</script>
{% endblock js %}

blogist/templates/blog/search.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Search results for `{{q}}`</h1>
        <p class="col-md-8 fs-4">
            <b>total articles</b>: {{articles|length}} articles
        </p>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-10 mx-auto">
            {% for item in articles %}
            <div class="card mb-3">
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="{% url 'view' item.id %}" class="nav-link">
                            {{item.title}}
                        </a>
                    </h4>
                    <p class="card-text">
                        {{item.content|truncatechars:100|safe}}
                    </p>
                    <a href="{% url 'view' item.id %}" class="btn btn-primary">
                        Read more
                    </a>
                </div>
            </div>
            {% empty %}
            <div class="card mb-3">
                <div class="card-body">
                    <h4 class="card-title">
                        No articles found related to `{{q}}`
                    </h4>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</div>
{% endblock %}